version: '3'

services:
  cpp:
    container_name: cpp
    build: 
      context: ./
      dockerfile: DockerFile
    deploy:
      resources:
        limits:
          memory: 500MB
        reservations:
          memory: 200MB
    volumes: 
      - ./:/app
